[package]
name = "sync"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rfd = "0.14"

[build-dependencies]
embed-resource = "2.4"